name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]  # simplificamos a 20.x por ahora
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          # OJO: sin cache para evitar la advertencia del lockfile

      - name: Install dependencies (no lockfile needed)
        run: npm install --no-fund --no-audit

      - name: Run tests (with coverage + junit)
        run: npm run test:ci

      # Subimos artefactos solo si existen, para evitar warnings
      - name: Upload coverage
        if: ${{ always() && hashFiles('coverage/lcov.info') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage/

      - name: Upload junit
        if: ${{ always() && hashFiles('junit.xml') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: junit
          path: junit.xml
